config/routes.rb
Rails.application.routes.draw do
  root 'high_scores#index'
  resources :high_scores

end

app/models/high_score.rb
class HighScore < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/high_scores_controller.rb
class HighScoresController < ApplicationController
  before_action :set_high_score, only: [:show, :edit, :update, :destroy]

  # GET /high_scores
  # GET /high_scores.json
  def index
    @high_scores = HighScore.all
  end

  # GET /high_scores/1
  # GET /high_scores/1.json
  def show
  end

  # GET /high_scores/new
  def new
    @high_score = HighScore.new
  end

  # GET /high_scores/1/edit
  def edit
  end

  # POST /high_scores
  # POST /high_scores.json
  def create
    @high_score = HighScore.new(high_score_params)

    respond_to do |format|
      if @high_score.save
        format.html { redirect_to @high_score, notice: 'High score was successfully created.' }
        format.json { render :show, status: :created, location: @high_score }
      else
        format.html { render :new }
        format.json { render json: @high_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /high_scores/1
  # PATCH/PUT /high_scores/1.json
  def update
    respond_to do |format|
      if @high_score.update(high_score_params)
        format.html { redirect_to @high_score, notice: 'High score was successfully updated.' }
        format.json { render :show, status: :ok, location: @high_score }
      else
        format.html { render :edit }
        format.json { render json: @high_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /high_scores/1
  # DELETE /high_scores/1.json
  def destroy
    @high_score.destroy
    respond_to do |format|
      format.html { redirect_to high_scores_url, notice: 'High score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_high_score
      @high_score = HighScore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def high_score_params
      params.require(:high_score).permit(:game, :score)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/high_scores_helper.rb
module HighScoresHelper
end

app/views/high_scores/_form.html.haml
= simple_form_for(@high_score) do |f|
  = f.error_notification

  .form-inputs
    = f.input :game
    = f.input :score

  .form-actions
    = f.button :submit

app/views/high_scores/edit.html.haml
%h1 Editing high_score

= render 'form'

= link_to 'Show', @high_score
\|
= link_to 'Back', high_scores_path

app/views/high_scores/index.html.haml
%h1 Listing high_scores
%div{:class=>"container"}
  %table
    %thead
      %tr
        %th Game
        %th Score
        %th
        %th
        %th

    %tbody
      - @high_scores.each do |high_score|
        %tr
          %td= high_score.game
          %td= high_score.score
          %td= link_to 'Show', high_score
          %td= link_to 'Edit', edit_high_score_path(high_score)
          %td= link_to 'Destroy', high_score, :method => :delete, :data => { :confirm => 'Are you sure?' }

  %br

= link_to 'New High score', new_high_score_path

app/views/high_scores/new.html.haml
%h1 New high_score

%div{:class=>"container"}
	= render 'form'

= link_to 'Back', high_scores_path

app/views/high_scores/show.html.haml
%p#notice= notice

%p
  %b Game:
  = @high_score.game
%p
  %b Score:
  = @high_score.score

= link_to 'Edit', edit_high_score_path(@high_score)
\|
= link_to 'Back', high_scores_path

app/views/layouts/-application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>prueba</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
	%head
		%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
		%title Probando con git
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tags
	%body
		%div.container
			.nav-collapse.collapse
				%ul.nav
					%li.active
						%a{:href => "#"}
							Home
					%li.dropdown
						%a.dropdown-toggle{:href => "#", "role" => "button", "data-toggle" => "dropdown", "data-target" => "#"}
							Dropdown
							%b.caret
						%ul.dropdown-menu{"role" => "menu"}
							%li
								%a{:href => "#link1"}
									Dropdown #1
							%li
								%a{:href => "#link2"}
									Dropdown #2
							%li
								%a{:href => "#link3"}
									Dropdown #3
							%li
								%a{:href => "#link4"}
									Dropdown #4
						%li
							%a{:href => "#contact"}
								Contact
			= yield